name: Check code with eslint & pretter

on:
  pull_request:
    branches:
      - 'master'

jobs:
  formatting:
    name: Run source scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          # 아래 키값으로 cache가 돼있는지 확인합니다.
          key: pnpm-packages-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run ESLint
        run: |
          pnpm lint
          echo "ESLint Completed!"

      - name: Run Prettier
        run: |
          pnpm format
          echo "Prettier Completed!"
